# Generated by Django 2.2.10 on 2020-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[(1, 'Technical Head'), (2, 'Webmaster'), (3, 'Events Head')], default=1, max_length=9)),
            ],
        ),
    ]
