# Generated by Django 2.2.10 on 2020-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.IntegerField(choices=[(0, 'Choose an option'), (1, 'Technical Head ACM'), (2, 'Technical Head ACM-W'), (3, 'Webmaster ACM'), (4, 'Webmaster ACM-W'), (5, 'Events Head ACM'), (6, 'Events Head ACM-W'), (7, 'PR Head ACM'), (8, 'PR Head ACM-W')], default=0),
        ),
    ]
