# Generated by Django 2.2.10 on 2020-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mode',
            field=models.CharField(choices=[(1, 'Online Event'), (2, 'Offline Mode')], default='Choose an option', max_length=10),
        ),
    ]
