# Generated by Django 2.2.10 on 2020-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200403_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mode',
            field=models.CharField(choices=[(0, 'Choose an option'), (1, 'Online Event'), (2, 'Offline Mode')], default=0, max_length=10),
        ),
    ]
