# Generated by Django 2.2.10 on 2020-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200403_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Choose an option'), (1, 'Online Event'), (2, 'Offline Mode')], default=0),
        ),
    ]
